[build]
  publish = "dist"
  command = "npm run build"

[context.production]
  environment = { NODE_VERSION = "16.16.0" }

# [[headers]]
#   for = "/*"
#   [headers.values]
#     X-Frame-Options = "SAMEORIGIN"
#     X-Content-Type-Options = "nosniff"
#     Content-Security-Policy = "default-src 'self'; style-src 'self'; form-action 'self'; script-src 'self'; connect-src 'self'; img-src 'self'; base-uri 'self';"
